// @generated
// This file is @generated by prost-build.
/// Actionable instruction packet generated by Galadril after analytical inference.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GaladrilCommand {
    /// Unique command sequence identifier for idempotency and tracking.
    #[prost(uint64, tag="1")]
    pub command_id: u64,
    /// Microseconds since Unix Epoch when the command was generated.
    #[prost(uint64, tag="2")]
    pub timestamp_us: u64,
    /// Target identifier. Set to 0 for swarm-wide broadcast, or specific node ID.
    #[prost(uint32, tag="3")]
    pub target_node_id: u32,
    /// Categorized nature of the directive.
    #[prost(enumeration="CommandType", tag="4")]
    pub command_type: i32,
    /// Specific payload matching the assigned CommandType.
    #[prost(oneof="galadril_command::Directive", tags="5, 6, 7")]
    pub directive: ::core::option::Option<galadril_command::Directive>,
}
/// Nested message and enum types in `GaladrilCommand`.
pub mod galadril_command {
    /// Specific payload matching the assigned CommandType.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Directive {
        /// Used when command_type is COMMAND_TYPE_FORCE_MODE.
        #[prost(enumeration="super::super::super::super::ringil::swarm::v1::ActivityMode", tag="5")]
        ForcedMode(i32),
        /// Used when command_type is COMMAND_TYPE_STRATEGIC_GOAL.
        #[prost(message, tag="6")]
        StrategicGoal(super::super::super::super::ringil::swarm::v1::GeoPoint),
        /// Used when command_type is COMMAND_TYPE_RESTRICT_ZONE.
        #[prost(message, tag="7")]
        HazardZone(super::super::super::super::ringil::swarm::v1::MappingUpdate),
    }
}
/// Encapsulates the evaluation framework for the Go Kubernetes Operator.
/// This structure is read by the deployment controller to validate compatibility.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ManifestConstraint {
    /// Semantic version of the required interop protocol.
    #[prost(string, tag="1")]
    pub required_interop_version: ::prost::alloc::string::String,
    /// Min required Ringil firmware hash or version.
    #[prost(string, tag="2")]
    pub min_ringil_version: ::prost::alloc::string::String,
    /// Min required Galadril analytical model hash or version.
    #[prost(string, tag="3")]
    pub min_galadril_version: ::prost::alloc::string::String,
}
/// High-level wrapper frame for all Brain-to-Swarm intercommunication payloads.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InteropFrame {
    /// Tracking ID for the origin system.
    #[prost(uint32, tag="1")]
    pub source_system_id: u32,
    /// Microseconds since Unix Epoch for transport layer auditing.
    #[prost(uint64, tag="2")]
    pub timestamp_us: u64,
    /// Priority hint for Zenoh network infrastructure routing.
    #[prost(enumeration="super::super::super::ringil::swarm::v1::PriorityLevel", tag="3")]
    pub priority: i32,
    /// The actual payload of the interop communication frame.
    #[prost(oneof="interop_frame::Payload", tags="4, 5")]
    pub payload: ::core::option::Option<interop_frame::Payload>,
}
/// Nested message and enum types in `InteropFrame`.
pub mod interop_frame {
    /// The actual payload of the interop communication frame.
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Payload {
        /// Strategic order routed from Galadril to the swarm.
        #[prost(message, tag="4")]
        Command(super::GaladrilCommand),
        /// Infrastructure manifest used by Artemis for deployment validation.
        #[prost(message, tag="5")]
        DeploymentManifest(super::ManifestConstraint),
    }
}
/// Broad classification of strategic command directives issued by Galadril.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CommandType {
    /// Default state, invalid or unassigned command.
    Unspecified = 0,
    /// Overrides the swarm or unit activity mode.
    ForceMode = 1,
    /// Updates the global mission target coordinate.
    StrategicGoal = 2,
    /// Dynamically inserts or modifies a restricted area/No-Fly Zone.
    RestrictZone = 3,
    /// Triggers immediate recall of a unit or the entire swarm to base.
    ForceRecovery = 4,
    /// Manual telemetry request override bypassing current Zenoh priority queues.
    PollStatus = 5,
}
impl CommandType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "COMMAND_TYPE_UNSPECIFIED",
            Self::ForceMode => "COMMAND_TYPE_FORCE_MODE",
            Self::StrategicGoal => "COMMAND_TYPE_STRATEGIC_GOAL",
            Self::RestrictZone => "COMMAND_TYPE_RESTRICT_ZONE",
            Self::ForceRecovery => "COMMAND_TYPE_FORCE_RECOVERY",
            Self::PollStatus => "COMMAND_TYPE_POLL_STATUS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMMAND_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "COMMAND_TYPE_FORCE_MODE" => Some(Self::ForceMode),
            "COMMAND_TYPE_STRATEGIC_GOAL" => Some(Self::StrategicGoal),
            "COMMAND_TYPE_RESTRICT_ZONE" => Some(Self::RestrictZone),
            "COMMAND_TYPE_FORCE_RECOVERY" => Some(Self::ForceRecovery),
            "COMMAND_TYPE_POLL_STATUS" => Some(Self::PollStatus),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
