name: Passerelle CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Run Buf Checks
        uses: bufbuild/buf-action@v1
        with:
          breaking_against: 'https://github.com/${{ github.repository }}.git#branch=main'

  generate-and-deploy:
    needs: validate
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Buf
        uses: bufbuild/buf-action@v1
        with:
          setup_only: true

      - name: Generate Multi-Language Code
        run: buf generate

      - name: Commit and Push Generated Code
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatic protobuf code generation"
          branch: main
          file_pattern: 'rust/src/** go/** python/src/**'
          commit_user_name: "aeluin-bot"
          commit_user_email: "bot@gravitalia.com"
